name: Generate Production Keystore

on:
  workflow_dispatch:

jobs:
  create-key:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Key Using Keytool
      run: |
        keytool -genkey -v \
          -keystore hamed_release_key.jks \
          -alias hamedkhan978 \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass "86598Hsh@!" \
          -keypass "86598Hsh@!" \
          -dname "CN=Hamed, O=Production, C=IR"

    - name: Convert Keystore to Base64 Text
      run: |
        base64 -w 0 hamed_release_key.jks > keystore_base64.txt

    - name: Upload Keystore and Base64 Text
      uses: actions/upload-artifact@v4
      with:
        name: my-secure-keystore
        path: |
          hamed_release_key.jks
          keystore_base64.txt
